### ISSUE TITLE
Option in VM dict for packages

### ISSUE THREAD

**Issue by randyoyarzabal** [binbashroot/provision_promox#10]
An option in the VM dictionary to add repos (e.g. EPEL) and multi-value list of dnf packages.

**Comment by binbashroot** [comment]
This would/should be in a follow up role separate from provision itself.  The register playbook will eventually be decoupled as it was really more of a demo of concept.  Next steps will be to create an "R2"(R squared = Randy and Randy)  collection.  This collection will contain all of the config management related roles/tasks/playbooks.
