### ISSUE TITLE
The incorrect private key is being set in the dynamic inventory.

### ISSUE THREAD

**Issue by mdidato** [binbashroot/provision_promox#15]
in the site.yml file the servers ssh key is not set properly

The task below sets the host vars for the newrhelservers group

- name: Add host to dynamic inventory for a future run
       ansible.builtin.add_host:
              name: "{{ vm['name'] }}.{{ domain }}"
              groups: newrhelservers
              ansible_user: "{{ cloud_init_user }}"
              ansible_ssh_private_key_file: "{{ cloud_init_public_key }}"
              ansible_host: "{{ vm['ip_with_cidr']|ansible.utils.ipaddr('address') }}"
              provision_tags: "{{ vm['tags'] }}"
       loop: "{{ virtual_machines }}"

The ansible_ssh_private_key_file: "{{ cloud_init_public_key }}" line is setting the private key value to the public key. This causes the register.yml playbook to fail.  

I have a fix and will push it to the dev branch for review in the morning

**Comment by binbashroot** [comment]
fixed in features branch with latest pr
